# Generated by Django 5.0.2 on 2025-07-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('college', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('supervisor', models.CharField(max_length=100)),
            ],
        ),
    ]
