# Generated by Django 5.0.2 on 2025-07-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_workshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('project', models.TextField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('not_started', 'Not Started')], max_length=20)),
            ],
        ),
    ]
